"""Shared project settings for commute analysis and its notebooks."""

from datetime import date, datetime, time, timedelta
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
OSM_DATA_DIR = RAW_DATA_DIR / "osm"
MERGED_OSM_DIR = OSM_DATA_DIR / "merged"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

POPULATION_GRID_FILENAME = "population_grid.csv"
POPULATION_GRID_PATH = RAW_DATA_DIR / POPULATION_GRID_FILENAME
POPULATION_GRID_READ_SEPARATOR = None
POPULATION_GRID_CSV_ENGINE = "python"
DESTATIS_CSV_SEPARATOR = ";"
SYNTHETIC_EMPLOYEES_FILENAME = "synthetic_employees.gpkg"
SYNTHETIC_EMPLOYEES_PATH = PROCESSED_DATA_DIR / SYNTHETIC_EMPLOYEES_FILENAME
SCORING_TEST_EMPLOYEES_FILENAME = "synthetic_employees_scoring_test.gpkg"
SCORING_TEST_EMPLOYEES_PATH = PROCESSED_DATA_DIR / SCORING_TEST_EMPLOYEES_FILENAME
SCORING_TEST_OUTPUT_DIR = OUTPUTS_DIR / "transport_scores_test"
TRANSPORT_SCORE_OUTPUT_DIR = PROCESSED_DATA_DIR
ISOCHRONE_MAP_PATH = OUTPUTS_DIR / "isochrone_map.html"
ROUTE_MAP_PATH = OUTPUTS_DIR / "route_map.html"
TRANSPORT_SCORE_SUMMARY_FILENAME = "summary_gdf.gpkg"
TRANSPORT_SCORE_ROUTE_FILENAME = "route_gdf.gpkg"
GEOPACKAGE_DRIVER = "GPKG"
SYNTHETIC_EMPLOYEES_LAYER = "synthetic_employees"

CRS_WGS84 = "EPSG:4326"
CRS_POPULATION_GRID = "EPSG:3035"
CRS_LOCAL_METRIC = "EPSG:25832"
CRS_WEB_MERCATOR = "EPSG:3857"

WORKPLACE = (53.68623, 10.04602)
WORKPLACE_CRS = CRS_WGS84
ANALYSIS_RADIUS_KM = 50
POPULATION_COLUMN = "Einwohner"
SYNTHETIC_EMPLOYEE_COUNT = 100
SAMPLING_FILTER_MODE = "gaussian"
SAMPLING_GAUSSIAN_SCALE = 10_000
SAMPLING_RANDOM_SEED = None
POLYGON_SAMPLE_MAX_ATTEMPTS = 10_000
DEFAULT_POPULATION_FILTER_MODE = "uniform"
DEFAULT_GAUSSIAN_SCALE = None
RANDOM_SEED = 42
SCORING_MAX_WORKERS = 1
SCORING_SAVE_OUTPUTS = True
SCORING_OVERWRITE_OUTPUTS = True
DEFAULT_SCORING_MAX_WORKERS = None
DEFAULT_SAVE_SCORE_OUTPUTS = False
DEFAULT_OVERWRITE_SCORE_OUTPUTS = False

SERVICE_DATE = date(2026, 9, 15)
MORNING_START = time(7, 0)
MORNING_END = time(9, 0)
EVENING_START = time(16, 0)
EVENING_END = time(18, 0)
DEPARTURE_INTERVAL = timedelta(minutes=10)
ANALYSIS_ISOCHRONE_DEPARTURE = datetime(2026, 9, 15, 15, 30)
EXAMPLE_MORNING_DEPARTURE = datetime(2026, 9, 15, 8, 0)
EXAMPLE_EVENING_DEPARTURE = datetime(2026, 9, 15, 17, 15)

RELATIVE_TIME_WEIGHT = 0.25
ABSOLUTE_TIME_WEIGHT = 0.25
CONSISTENCY_WEIGHT = 0.30
WALKING_WEIGHT = 0.10
TRANSFERS_WEIGHT = 0.10
LOWER_SCORE_QUANTILE = 0.25
UPPER_SCORE_QUANTILE = 0.75
RELATIVE_TIME_RATIO_BEST = 1.0
RELATIVE_TIME_RATIO_WORST = 3.5
MAX_PUBLIC_TRANSPORT_TIME_MIN = 180.0
CONSISTENCY_RATIO_BEST = 1.0
CONSISTENCY_RATIO_WORST = 1.33
MAX_DAILY_WALKING_TIME_MIN = 60.0
MAX_DAILY_TRANSFERS = 8.0

OSM_PBF_FILENAMES = (
    "hamburg-260718.osm.pbf",
    "niedersachsen-260718.osm.pbf",
    "schleswig-holstein-260718.osm.pbf",
)
OSM_DOWNLOAD_URLS = {
    "hamburg-260718.osm.pbf": "https://download.geofabrik.de/europe/germany/hamburg-260901.osm.pbf",
    "niedersachsen-260718.osm.pbf": "https://download.geofabrik.de/europe/germany/niedersachsen-260901.osm.pbf",
    "schleswig-holstein-260718.osm.pbf": "https://download.geofabrik.de/europe/germany/schleswig-holstein-260901.osm.pbf",
}
GTFS_FILENAME = "hvv_Rohdaten_GTFS_Fpl_26.ZIP"
GTFS_DATASET_URL = "https://suche.transparenz.hamburg.de/dataset/hvv-fahrplandaten-gtfs-april-2026-bis-dezember-2026"
DESTATIS_POPULATION_ZIP_URL = "https://www.destatis.de/static/DE/zensus/gitterdaten/Zensus2022_Bevoelkerungszahl.zip"
DESTATIS_POPULATION_CSV_FILENAME = "Zensus2022_Bevoelkerungszahl_100m-Gitter.csv"
DOWNLOAD_TIMEOUT_SECONDS = 120
DOWNLOAD_CHUNK_SIZE_BYTES = 1024 * 1024
MERGED_OSM_FILENAME = "northern-germany.osm.pbf"
MERGED_OSM_PATH = MERGED_OSM_DIR / MERGED_OSM_FILENAME
OSMIUM_COMMAND = "osmium"
OVERWRITE_MERGED_OSM = True
ALLOW_ROUTING_DATA_ERRORS = True
DEFAULT_ROUTE_MODES = ("car", "bike")
SNAP_TO_NETWORK = True

REACHABILITY_TIME_WINDOW = timedelta(minutes=60)
REACHABILITY_RADIUS_M = 20_000
ANALYSIS_REACHABILITY_RADIUS_M = 19_000
REACHABILITY_GRID_STEP_M = 100
MAX_REACHABILITY_TIME_MIN = 60

assert abs(
    RELATIVE_TIME_WEIGHT
    + ABSOLUTE_TIME_WEIGHT
    + CONSISTENCY_WEIGHT
    + WALKING_WEIGHT
    + TRANSFERS_WEIGHT
    - 1.0
) < 1e-9, "Transport score weights must sum to 1.0"